---
# Manual PipelineRun for Challenge 2 — Chains variant
# Triggers push-build-pipeline-with-chains, which:
#   1. Builds and pushes the image (emitting IMAGE_URL + IMAGE_DIGEST)
#   2. Lets Tekton Chains sign the image and generate a SLSA Provenance attestation
#   3. Generates an SPDX JSON SBOM and attests it with cosign
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: push-build-chains-manual-
  namespace: ctf-challenge
  labels:
    tekton.dev/pipeline: push-build-pipeline-with-chains
    trigger-type: manual
spec:
  serviceAccountName: pr-pipeline-readonly
  pipelineRef:
    name: push-build-pipeline-with-chains
  params:
    - name: repo-url
      value: http://gitea-http.gitea.svc.cluster.local:3000/ctf-admin/recipe-api.git
    - name: revision
      value: main
    - name: image-name
      value: recipe-api
    - name: image-tag
      value: v1.0
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
