---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-pipeline-sa
  namespace: release-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-pipeline-role
  namespace: release-pipeline
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "list"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-pipeline-rolebinding
  namespace: release-pipeline
subjects:
  - kind: ServiceAccount
    name: release-pipeline-sa
    namespace: release-pipeline
roleRef:
  kind: Role
  name: release-pipeline-role
  apiGroup: rbac.authorization.k8s.io
