apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    ctf-challenge: challenge4

---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: production
    ctf-challenge: challenge4
